package platine.zoo.animal_api.bo;

import org.junit.jupiter.api.Test;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class VisibleTest {
    @Test
    void visible_shouldBeAnEntity(){
        assertNotNull(Visible.class.getAnnotation(MappedSuperclass.class));
    }

    @Test
    void visibleId_shouldBeAnIdAndAutoGeneratedValue() throws NoSuchFieldException {
        assertNotNull(Visible.class.getDeclaredField("id").getAnnotation(Id.class));
        assertNotNull(Visible.class.getDeclaredField("id").getAnnotation(GeneratedValue.class));
    }

}
